export {default as background} from "./src/backgrounds";
export {default as basicLine} from "./src/basic-line";
export {default as basicLineSocial} from "./src/basic-line-social";
export {default as categorical} from "./src/categorical";
export {default as diverging} from "./src/diverging";
export {default as sequentialMulti} from "./src/sequential-multi";
export {default as sequentialSingle} from "./src/sequential-single";
export {default as sequentialSingle_teal} from "./src/sequential-single__teal";
export {default as ukPoliticalParties} from "./src/categorical-uk-politics";